; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB

build_flags = 
    -I src/motor
    -I src/encoder
    -I src/ibus
    -I src/kinematics
    -I src/logger
    -I src/wifi
    -I src/rasp_uart
    -I src/imu
    -I src/led_buzzer
    -I src/ultrasonic
    -I src/tests
    -I src/manual_control

    -DTEST_MODE
    ; -DTEST_MOTOR    ; chỉ đổi dòng này
    ; -DTEST_ENCODER  ; chỉ đổi dòng này
    ; -DTEST_IBUS     ; chỉ đổi dòng này  
    ; -DTEST_KINEMATICS ; chỉ đổi dòng này
    ; -DTEST_LOGGER   ; chỉ đổi dòng này
    ; -DTEST_WIFI     ; chỉ đổi dòng này
    ; -DTEST_RASP_UART ; chỉ đổi dòng này
    ; -DTEST_IMU      ; chỉ đổi dòng này
    ; -DTEST_LED_BUZZER ; chỉ đổi dòng này
    ; -DTEST_ULTRASONIC ; chỉ đổi dòng này
    -DTEST_MANUAL ; chỉ đổi dòng này

